[toolchain]
channel = "1.92.0" # See workspace Cargo.toml
components = ["rust-src", "rust-analyzer"]
profile = "default"
targets = ["x86_64-pc-windows-msvc", "aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
