[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

# https://jake-shadle.github.io/xwin
[target.x86_64-pc-windows-msvc]
linker = "lld-link" # Note the lack of extension, which means it will work on both Windows and unix style platforms
