[package]
name = "rvid-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A rust based wireless PCVR solution"
publish = false

[dependencies]
