name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check --all

  check:
    name: Lint and Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v15
        with:
          name: nexus-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Print env
        run: nix develop -c env
      - name: Clippy lints
        run: |
          nix develop -c \
            cargo clippy --all --all-features --all-targets --no-deps -- -D warnings

      - name: Cargo Doc
        run: |
          nix develop -c bash -c \
            'RUSTDOCFLAGS="-D warnings" cargo doc --all --all-features --no-deps --document-private-items'

  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v15
        with:
          name: nexus-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Print env
        run: nix develop -c env

      - name: Test
        run: |
          nix develop -c \
            cargo test --all --all-features --all-targets

  deny:
    name: Run cargo deny
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: EmbarkStudios/cargo-deny-action@v2
